// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_subsetsC
List generate_subsetsC(IntegerVector set);
RcppExport SEXP _SA24204150_generate_subsetsC(SEXP setSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type set(setSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_subsetsC(set));
    return rcpp_result_gen;
END_RCPP
}
// generate_nested_subsetsC
List generate_nested_subsetsC(IntegerVector set);
RcppExport SEXP _SA24204150_generate_nested_subsetsC(SEXP setSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type set(setSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_nested_subsetsC(set));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204150_generate_subsetsC", (DL_FUNC) &_SA24204150_generate_subsetsC, 1},
    {"_SA24204150_generate_nested_subsetsC", (DL_FUNC) &_SA24204150_generate_nested_subsetsC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204150(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
