# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generate all non-empty subsets (Rcpp)
NULL

#' @title Generate nested subsets (Rcpp)
NULL

generate_subsetsC <- function(set) {
    .Call(`_SA24204150_generate_subsetsC`, set)
}

generate_nested_subsetsC <- function(set) {
    .Call(`_SA24204150_generate_nested_subsetsC`, set)
}

